apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
  namespace: xeelver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
        version: "1"
    spec:
      serviceAccountName: booking
      containers:
        - name: booking
          image: marmiss/booking-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
