apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  labels:
    app: frontend-server
  namespace: xeelver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
        version: "1"
    spec:
      serviceAccountName: frontend-server
      containers:
        - name: frontend-server
          image: marmiss/frontend:1.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
