apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
  namespace: xeelver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        version: "1"
    spec:
      serviceAccountName: payment
      containers:
        - name: payment
          image: marmiss/payment-service:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            env:
              - name: KLARNA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: klarna-secret
                    key: username
              - name: KLARNA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: klarna-secret
                    key: password
