apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        tier: backend
    spec:
      containers:
        - name: payment
          image: marmiss/payment-service:1.0.0
          ports:
            - containerPort: 80
