apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
        tier: backend
    spec:
      containers:
        - name: search
          image: marmiss/search-service:1.0.0
          ports:
            - containerPort: 80
