apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
  namespace: xeelver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
        version: "1"
    spec:
      serviceAccountName: search
      containers:
      - name: search
        image: marmiss/search-service:1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: AMADEUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: key
        - name: AMADEUS_API_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cache-secret
              key: password
