apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-server
  name: frontend-server
  namespace: xeelver
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend-server
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-server
  namespace: xeelver