apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
  namespace: xeelver
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: payment
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  namespace: xeelver