apiVersion: v1
kind: Service
metadata:
  labels:
    app: search
  name: search
  namespace: xeelver
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: search
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search
  namespace: xeelver