apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: http://35.242.190.130:8080/auth/realms/react
    jwksUri: http://35.242.190.130:8080/auth/realms/react/protocol/openid-connect/certs
